// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userclient

import (
	"context"

	"thumbup/service/user/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	InfoRequest      = user.InfoRequest
	InfoResponse     = user.InfoResponse
	RegisterRequest  = user.RegisterRequest
	RegisterResponse = user.RegisterResponse

	User interface {
		Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Info(ctx, in, opts...)
}
