// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"thumbup/service/thumbup/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/thumbup/action",
				Handler: ActionHandler(serverCtx),
			},
		},
	)
}
