// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideo = "video"

// Video mapped from table <video>
type Video struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	VideoID    int64     `gorm:"column:video_id;not null" json:"video_id"`
	AuthorID   int64     `gorm:"column:author_id;not null" json:"author_id"`
	Title      string    `gorm:"column:title;not null" json:"title"`
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
