// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideoCount = "video_count"

// VideoCount mapped from table <video_count>
type VideoCount struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	VideoID       int64     `gorm:"column:video_id;not null" json:"video_id"`
	FavoriteCount int64     `gorm:"column:favorite_count;not null" json:"favorite_count"`
	CreateTime    time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime    time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName VideoCount's table name
func (*VideoCount) TableName() string {
	return TableNameVideoCount
}
