// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"zouyi/thumbup/service/user/rpc/internal/logic"
	"zouyi/thumbup/service/user/rpc/internal/svc"
	"zouyi/thumbup/service/user/rpc/types/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Info(ctx context.Context, in *user.InfoRequest) (*user.InfoResponse, error) {
	l := logic.NewInfoLogic(ctx, s.svcCtx)
	return l.Info(in)
}
