// Code generated by goctl. DO NOT EDIT.
package types

type RegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Id           int64  `json:"id"`
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type InfoResponse struct {
	Name string `json:"name"`
}
